apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: betteruptime
spec:
  schedule: "0 2 * * *"  # Run backup every day at 2 AM UTC
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: postgres-backup
              image: postgres:15
              env:
                - name: POSTGRES_HOST
                  value: "postgres"
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: database-secret
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: database-secret
                      key: POSTGRES_DB
              command:
                - /bin/bash
                - -c
                - |
                  export PGPASSWORD=$POSTGRES_PASSWORD
                  BACKUP_FILE="/backup/backup-$(date +%Y%m%d-%H%M%S).sql"
                  echo "Creating backup: $BACKUP_FILE"
                  pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB > $BACKUP_FILE
                  echo "Backup completed successfully"

                  # Keep only last 7 days of backups
                  find /backup -name "backup-*.sql" -mtime +7 -delete
                  echo "Old backups cleaned up"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: postgres-pvc