apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init
  namespace: betteruptime
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: postgres-init
        image: aabhii/betteruptime-init:amd64-latest
        env:
          - name: DATABASE_URL
            value: "postgres://postgres:postgres@postgres:5432/mydb"
        command: ["/app/postgres-init.sh"]
      # Wait until Postgres pod is ready
      initContainers:
      - name: wait-for-postgres
        image: aabhii/betteruptime-init:amd64-latest
        command: ["/app/wait-for-postgres.sh", "postgres", "5432", "postgres"]